services:
  db:
    image: postgres:15
    container_name: agenda-db
    environment:
      POSTGRES_DB: agenda
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tonito
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d agenda"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: agenda-api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/agenda
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=tonito
      - JWT_SECRET=uma-chave-muito-mais-segura-no-docker-123
      - ADMIN_EMAIL=admin@sistema.com
      - ADMIN_PASSWORD=admin123

volumes:
  pgdata: